[package]
name = "netlib"
version = "0.1.0"
authors = ["Togglebit <me@togglebit.io>"]
edition = "2018"

[profile.release]
# debug = true
panic = 'abort'

[dependencies]
libc = "0.2.80"
log = "0.4.11"
net2 = "0.2.37"
