[package]
name = "netlib"
version = "0.1.0"
authors = ["Togglebit <me@togglebit.io>"]
edition = "2018"

[profile.release]
# debug = true
panic = 'abort'

[dependencies]
libc = "0.2.80"
crossbeam = "0.8.0"
parking_lot = "0.11.1"
